### ISSUE TITLE
Unit: why some getter methods are final?

### ISSUE THREAD

**Issue by GassaFM** [Russian-AI-Cup-2016/java-cgdk-ru#2]
В классе Unit почему-то эти getter методы final:
~~~~
public final double getX()
public final double getY()
public final double getSpeedX()
public final double getSpeedY()
public final double getAngle()
~~~~

А другие getter методы, как и getter методы других классов, не final:

~~~~
public long getId()
public Faction getFaction()
~~~~

Насколько я понимаю, final в определении метода означает, что метод нельзя переопределить в child-классах.
Но в чём смысловая разница между верхними пятью и нижними двумя методами, из-за которой два нижних теоретически можно переопределять?
Или это просто ни на что не влияющая опечатка, и все методы имелись в виду одинаковыми по критерию final?

**Comment by SladeThe** [comment]
Наличие/отсутствие final тут ни на что не влияет. Действительно, это просто опечатка.
